### PR TITLE
Remove dependency on jQuery, rewrite JS, polyfill for IE.

### PR DESCRIPTION
**Pull request by lpar**
Disclaimer: You might not want these changes as they're fairly major.

 - The jQuery search code has been replaced with shorter vanilla JS code which uses the HTML5 template element and DOM document fragment APIs. Template slots are now located and filled via `querySelector` and DOM operations, rather than jQuery templating.
 - The new code should work in all current browsers. Polyfills have been added for IE 11 and tested against it, and are only loaded for that browser.
 - MarkJS has been upgraded to 9.0.0 and switched to the Vanilla JS flavor.
 - jQuery is removed. You can, of course, still load and use jQuery elsewhere on your site, but you no longer need it in order to use this search implementation. (This is why I did this work.)
 - The README has been expanded a bit. I switched it to GitHub flavored Markdown because I think more people know that than Org mode, including me; I guess you could always convert it back using pandoc if you feel strongly about it.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Wow! First of all, thanks for putting in time and effort to submit this PR.

I am not a JS coder. So all the JS work is just ported from https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae.

Given that, I pulled in this PR locally and tried running the search in localhost. But it did not work. If I reverted back to my local master, the search in localhost started working again.

Can you provide a set of instructions to have this PR working in localhost? Or is this PR missing something?

**Comment by kaushalmodi** [comment]
I get this error in the localhost when I click in the search field: 
image

The error is originating from this line:

image

I need to be on Firefox ESR 45.0.1 (work system).

**Comment by lpar** [comment]
That's not part of the code. If I do a search using `ag` for `text2frag`, or even `node:node`, there are no matches. Is it possible that something else in your site is depending on jQuery?

For me, it works on localhost, either using `hugo server` or using `caddy` to preview. (There's a strange problem where you get doubling of search results using `hugo server`, but the old code also did that; I assume it's something to do with how hugo serves things up.)

**Comment by kaushalmodi** [comment]
> That's not part of the code. 

Sorry. You are right. That error is originating from a different part of the JS libs and it is showing up when I revert your commit locally too.

So that I not what's causing the issue. But the fact is that the search doesn't work if I checkout your commit.

Hmm.. looks like I need to figure out the source of the failure.

**Comment by lpar** [comment]
Demo repo of a site with search that should work is at https://github.com/lpar/hugo-with-search-demo

**Comment by kaushalmodi** [comment]
@lpar I attempted to show you the non-working version here: https://5cbf7108795360000723a774--scripter-co.netlify.com/search

**Comment by kaushalmodi** [comment]
@lpar Actually the CSP is blocking most of the content on that test site right now .. Please ignore that test site (but that shouldn't matter on localhost). I'll play with your test site in the meanwhile. Thanks.

**Comment by lpar** [comment]
If I turn off CSP I find that the test site is still loading the old search.js.

**Comment by kaushalmodi** [comment]
@lpar 

> If I turn off CSP I find that the test site is still loading the old search.js.

I believe that the test site was still referring to the old search.js from https://scripter.co (the currently deployed site that still uses the old search)?

I cloned your demo site and tried doing the search in there. In below GIF, you can see me searching for "leverage" (an arbitrary word that I found on your site), and it is not working.

search_does_not_work


So, may be it's my Firefox ESR 45.0 browser? Unfortunately that's the only browser I have in my devel env.

**Comment by kaushalmodi** [comment]
And I confirm that your demo site is loading the correct search.js:

image

**Comment by lpar** [comment]
So, what version of what browser are you using? Firefox ESR 45? That's probably the problem.

**Comment by kaushalmodi** [comment]
>  Firefox ESR 45? That's probably the problem.

Yes. So is it that Firefox ESR 45 doesn't understand the new JS syntax?

**Comment by lpar** [comment]
Can you see what error you get in the console? It might be easily fixed with an existing polyfill.

**Comment by kaushalmodi** [comment]
Interestingly no error is thrown except for "The connection to ws://:localhost:../livereload was interrupted while the page was loading" error, which I have always been getting.

**Comment by lpar** [comment]
OK, against my better judgement I downloaded Firefox ESR 45 (which is unsupported and has unpatched security issues) and worked out the problem and fixed it.

**Comment by lpar** [comment]
...and that means one of the polyfills is no longer needed for IE either.

**Comment by kaushalmodi** [comment]
Thanks so much for that extra effort and I'm sorry on the behalf of my Linux system admins that you needed to download a deprecated version of Firefox.

I'm now away from my PC, but I'll review and merge this as soon as I get to work tomorrow.

**Comment by kaushalmodi** [comment]
> ...and that means one of the polyfills is no longer needed for IE either.

Great! So that referenced min.js can also be removed then.

**Comment by kaushalmodi** [comment]
@lpar Many thanks for all your work on this!

Especially, thank you for the detailed info in https://github.com/kaushalmodi/hugo-search-fuse-js/pull/3#issue-272861462. I like your git PR etiquette!

I have manually merged your commits, so closing this PR.

**Pull request merged**
