### PR TITLE
Use module imports to get js libs

### LINKED ISSUE #15: Mount external JavaScripts using module system
`hugo mod -get -u` should be `hugo mod get -u` the first command will fail.

### PR DESCRIPTION
**Pull request by kaushalmodi**
Fixes https://github.com/kaushalmodi/hugo-search-fuse-js/issues/15

### CODE REVIEW

**Comment by kaushalmodi** [comment]
@Robin-Wils I have a test Hugo site deployed using this PR at https://use-module-imports-to-get-js-libs--hugo-search-fuse-js.netlify.app/.

But the search with the latest libs isn't as good as on the current versions of the libs: hugo-search-fuse-js.netlify.app/.

Example: Compare

- https://hugo-search-fuse-js.netlify.app/search/?q=heading , and
- https://use-module-imports-to-get-js-libs--hugo-search-fuse-js.netlify.app/search/?q=heading

If you have more insight into those JS libs and how to fix this, please let me know.

**Comment by kaushalmodi** [comment]
After rolling back the Fuse.js to v3.2.1 by running `hugo mod get github.com/krisk/Fuse@ec5d1a7079a03784e7a3e6778b428cad8774d881`, the search started working once again.

I will leave it up to a JS knowledgeable person to help upgrade the Fuse.js dep from 3.2.1 to 6.5.3 (details in https://github.com/kaushalmodi/hugo-search-fuse-js/issues/19).

Until then, this change from the js files in static to resources in assets mounted using Hugo Modules works just fine.

**Comment by Robin-Wils** [comment]
image
Both sites show the same for me. Are you user you don't have any cache? (ctrl+f5, instead of f5)

**Comment by kaushalmodi** [comment]
@Robin-Wils oops, https://use-module-imports-to-get-js-libs--hugo-search-fuse-js.netlify.app/search/?q=heading is now deployed with the rolled back Fuse.js.

It was rolled back in https://github.com/kaushalmodi/hugo-search-fuse-js/pull/18/commits/e6395abe48865a055252f2e9b35491c359a87ebf.

See the steps in https://github.com/kaushalmodi/hugo-search-fuse-js/issues/19 to reproduce the issue.

**Pull request merged**
