### PR TITLE
Exclude org toc from search results

### PR DESCRIPTION
**Pull request by Robin-Wils**
It should fix results like this. I do use the same thing on my branch. This specific feature branch is not tested yet. My site's submodules still have problems, so that's why it is not tested yet.

It is possible to make it an optional parameter, but I don't think it is needed, as it shouldn't hurt users which do not use org-mode.
image

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Ah! It makes sense; I am using something similar to auto-derive summaries: https://github.com/kaushalmodi/hugo-bare-min-theme/blob/master/layouts/partials/summary_minus_toc.html

 Ref: https://ox-hugo.scripter.co/doc/org-toc/#excluding-org-generated-toc-from-hugo-summaries

I'll take a look at this within a week, test it out and merge. 

Thanks!

**Comment by Robin-Wils** [comment]
If you already had code for that it could make sense to give this the same naming. If multiple theme modules have the same files, the theme at the top gives the user the file according to what I found about Hugo modules. It is also possible to exclude or include specific files from themes.

**Comment by kaushalmodi** [comment]
@Robin-Wils I have pulled in your commit from this PR into a separate PR: https://github.com/kaushalmodi/hugo-search-fuse-js/pull/17

It has some fixes on top of your commit.

**Comment by Robin-Wils** [comment]
Amazing. My site also builds again! Will look at other parts of my old pull-request soon, possibly tomorrow.

**Comment by Robin-Wils** [comment]
Nevermind, my search is broken, but it at least builds. 
image

**Comment by kaushalmodi** [comment]
If you have checked out the latest **main** branch, you should be seeing cache-busted JS being loaded:

image

This is from https://hugo-search-fuse-js.netlify.app/search/.

**Comment by kaushalmodi** [comment]
If you have go 1.12 or newer installed, this should work:

```
git clone https://github.com/kaushalmodi/hugo-search-fuse-js
cd hugo-search-fuse-js/exampleSite
./srv.sh
```

**Comment by Robin-Wils** [comment]
Yeah, managed to fix it. Had to disable some stuff in netlify though, since I don't accept requests from their CDN, but the JS was served through that.

**Comment by Robin-Wils** [comment]
Hmm with that disabled it is still broken lmao. Well, it will be something for tomorrow evening. No errors anymore though.

**Comment by Robin-Wils** [comment]
Ah, I see also the high Fuse.js problem. https://www.robinwils.com/js/libs/fuse.min.e3ffe275857f00d215368b38a182ac1950c7249fe2e7b019daebada5dfe79afd.js

Will check tomorrow evening, also did a rollback. It might be possible to just take what we need instead of the whole library.

**Pull request closed without merging**
